- id: mamushi
  name: format vyper
  description: "Run 'mamushi' for Vyper formatting"
  entry: mamushi
  language: python
  # types: [ vyper ]
  files: "\\.(vy|vyi)$"  # remove when type `vyper` available
  # additional_dependencies: ['identify==2.6.8']
