# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Run Black
      run: black --check ./src ./tests
      
    - name: Lint with flake8
      run: flake8 ./src ./tests
      if: always()
      
    - name: mypy
      run: |
        mypy ./src ./tests
        
    - name: Test with pytest
      run: |
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
